### ISSUE TITLE
Expecting afterInfinityModel to behave like Ember.Route.afterModel

### ISSUE THREAD

**Issue by gmurphey** [ember-infinity/ember-infinity#178]
Thank you for this addon! It's been incredibly useful and easy to implement.

I'm using `afterInfinityModel` to load relationships needed for the template. The way I've done this with `Ember.Route.afterModel` is:

``` javascript
afterModel(model) {
  return RSVP.allSettled(model.getEach('rel'));
}
```

However, with `afterInfinityModel`, I've had to do the following:

``` javascript
afterInfinityModel(model) {
  return RSVP.allSettled(model.getEach('rel')).then(() => model);
}
```

It seems that whatever is returned by `afterInfinityModel` is then used as the model object, whereas, if we want it to match the `afterModel` API, I believe model should remain as whatever is returned from the store.

If I can get feedback on whether this is intended or not, I'm happy to update the documentation / code.

Thanks again!

**Comment by hhff** [comment]
hi @gmurphey - yup - this is expected behavior.  Good point - this is slightly different to the `afterModel` hook.  I'd love a PR to update the docs~

TY!  👍

**Comment by snewcomer** [comment]
I believe afterInfinityModel can either be a promise or not now in 1.0!  Lmk if you have any questions
