### ISSUE TITLE
Constant Loading on IE 11 

### ISSUE THREAD

**Issue by BWieber** [ember-infinity/ember-infinity#200]
Internet Explorer does not wait for me to scroll to the bottom of the screen before loading more records -- it simply starts firing one after the other, loading all records in batches determined by `perPage`.

In Chrome, the scrolling function works fine.

**Comment by hhff** [comment]
Interesting.  What are you seeing on Firefox & Safari?

Is your "scrollable" area in an overflow-hidden div?

**Comment by snewcomer** [comment]
@BWieber Just tried on IE11.  With the 1.0.0-alpha releases something may have changed.  Lmk if you are still seeing this problem and we can tackle it!

**Comment by BWieber** [comment]
Thanks @snewcomer ! Looks good to me too :)
