### ISSUE TITLE
Support for multiple infinity-models?

### ISSUE THREAD

**Issue by deepflame** [ember-infinity/ember-infinity#202]
Hey guys,

as far as I understand `ember-infinity` is working with RSVP.hash in the model hook. Then I can specify the infinity model with `modelPath` in the router.

However can I also have multiple infinity models in RSVP.hash? Guess not as there is no way to specify both paths, right?

Thanks
Andreas

**Comment by hhff** [comment]
hi @deepflame - that's correct.  Right now - we're limited to one infinity model per route.

That said - I have an experimental branch that supports multiple models (that I'm using in production) here: https://github.com/hhff/ember-infinity/tree/feature/modularize-infinity-model

Of course - it's totally alpha, it's a big rewrite of the Ember Infinity internals.  I'm working to stabilize this work without breaking changes - and thus I can't really provide any major help or support with it until it's released.

That said, if you'd like to contribute to the branch - I'd love for you to take a look at it!~

**Comment by deepflame** [comment]
HI @hhff , thanks for the reply and the explanation. Well, in the meantime I have implemented a custom solution for it.
Yeah, would be nice to have it right in `ember-infinity`.

**Comment by hhff** [comment]
Cool!  I'm going to leave this open until I've got the new feature branch merged in!

**Comment by snewcomer** [comment]
@deepflame This feature should be enabled in `1.0.0-alpha.6`!  Lmk if you run into any problems.

**Comment by snewcomer** [comment]
Added to readme.  https://github.com/ember-infinity/ember-infinity/blob/master/README.md
