### ISSUE TITLE
Caching results of InfinityModel (via store#query)?

### ISSUE THREAD

**Issue by alizahid** [ember-infinity/ember-infinity#204]
Right now, every time I go to a route using `infinityModel`, it fetches the data from the server and then renders. Can I enable caching with my adapter's `shouldBackgroundReloadAll` method to show the cached stuff and then the updated content?

**Comment by hhff** [comment]
Good Q @alizahid - I've not implemented caching because I have been hoping Ember Data could do this on the lower level (we use `this.store.query` under the hood).

https://github.com/emberjs/data/issues/1966#issuecomment-219394961

once Ember Data supports it, we should too!

**Comment by snewcomer** [comment]
@alizahid This should be be worked into 1.0 now!  with the `infinityCache` key (README).  Lmk if you have any questions.
