### ISSUE TITLE
Entire model loaded with text "Infinite Model Entirely Loaded" without scrolling down.

### ISSUE THREAD

**Issue by syedasadhasan** [ember-infinity/ember-infinity#239]
I was testing to implement it as described in basic usage section but when page loads entire model loaded with text "Infinite Model Entirely Loaded" without scrolling down. Pls help in resolving the issue.

**Comment by snewcomer** [comment]
@syedasadhasan Thanks for putting out the question to us!  I would guess that your response says it only has 1 page....so the total pages to load is equal to the current page.

https://github.com/hhff/ember-infinity/blob/master/addon/mixins/route.js#L144

Let me know if that isn't the case and I'll try to help some more.

**Comment by syedasadhasan** [comment]
This is my route. There are 22 records in my data.
----------------------------------------------------------------
import Ember from 'ember';
import InfinityRoute from "ember-infinity/mixins/route";

export default Ember.Route.extend(InfinityRoute,{
    model: 
     function () {
   retrun this.infinityModel('users', {
          perPage: 5,
          startingPage: 1, 
        })
}
});

**Comment by snewcomer** [comment]
@syedasadhasan so one way to get to the bottom of this would be to reproduce your code with an [ember-twiddle](http://ember-twiddle.com/).

Also refer to the dummy app for examples.  https://github.com/hhff/ember-infinity/tree/master/tests/dummy/app

**Comment by syedasadhasan** [comment]
I can give you the code snippet if you want but to reproduce with ember-twiddle is difficult.

**Comment by snewcomer** [comment]
@syedasadhasan yeah its rather hard to debug from my end without a concrete example.

The best I can help with is pointing you to the examples [here](https://github.com/hhff/ember-infinity/tree/master/tests/dummy/app)

If you did post your code snippets (formatted) here, I could probably help!  👍

**Comment by snewcomer** [comment]
@syedasadhasan any update here?  Did you get this working?

**Comment by svparijs** [comment]
I currently have a similar issue. In the background everything is loaded without a scroll action.

**Comment by snewcomer** [comment]
@svparijs Ah dang!  what version of `ember-infinity` are you on (we are moving towards a 1-0 [release](https://github.com/hhff/ember-infinity/tree/1-0))?

Also what is your `scrollable` container?  I can try working on an ember-twiddle if it makes sense.

**Comment by hhff** [comment]
@snewcomer i wonder if this is related to that ember change we saw with our tests?  Remember we had to pin the ember version so that the tests would pass? 

It seems a specific version of ember introduced a change to the way DOM measurement happens.  We should find that version and polyfill or fix backward compatibly

**Comment by hhff** [comment]
Moving to Ember In Viewport probably solves this

**Comment by snewcomer** [comment]
@hhff I agree.  I found that ember-cli-qunit 3.0.1 or 2.2.2 works; anything above fails.  #240 I'll work on this this weekend and probably dig into what is different with those qunit versions on the 1-0 branch.

**Comment by snewcomer** [comment]
@syedasadhasan @svparijs Here is a branch `ember-in-viewport` that you could try replacing in your application to see if anything is fixed.

in your package.json
`"ember-infinity": "git+ssh://git@github.com:hhff/ember-infinity.git#ember-in-viewport"`

**Comment by snewcomer** [comment]
@syedasadhasan We released `1.0.0-alpha.4` today.  Lmk if this help.  Will close this issue for now but feel free to re-open if you would like.
