### ISSUE TITLE
Look into replacing/modifying our infinity-loader with ember-in-viewport

### ISSUE THREAD

**Issue by snewcomer** [ember-infinity/ember-infinity#240]
Based on a comment from @Duder-onomy, it may be a good idea to replace/modify our custom infinity-loader component to work with this addon.  

https://github.com/DockYard/ember-in-viewport

Note: We are working on a 1-0 [branch](https://github.com/hhff/ember-infinity/tree/1-0) so any further work should be based on that branch.

**Comment by Duder-onomy** [comment]
Might be worth looking into : https://github.com/asakusuma/ember-spaniel
Uses intersection observers with a RAF fallback.

**Comment by snewcomer** [comment]
Will be tackling this weekend on the 1-0 branch.

**Comment by snewcomer** [comment]
@Duder-onomy Still waiting for this upstream PR.  Feel free to review if you have time.

https://github.com/DockYard/ember-in-viewport/pull/113

Once #242 is merged, it will be a huge perf win, esp for large lists.

**Comment by Duder-onomy** [comment]
That PR looks great. Looks like allot of work. But if you can get that PR in to a ember lib as popular as `ember-in-viewport`.... that would be gangster. 

Sorry if I don't understand, but what is stopping `ember-infinity` from using `ember-in-viewport` right now?

**Comment by snewcomer** [comment]
@Duder-onomy  No scrollable area (that PR adds it).

**Comment by Duder-onomy** [comment]
Ahhh. Rawk.

**Comment by snewcomer** [comment]
Addedd!  @Duder-onomy Released w/ `1.0.0-alpha.4`

**Comment by Duder-onomy** [comment]
@snewcomer This looks great! Pulled in the `1.0.0-alpha.4` release and everything looks great in our app. Good work with that ember-in-viewport PR.
