### ISSUE TITLE
Unit, integration and acceptance test examples

### ISSUE THREAD

**Issue by williamweckl** [ember-infinity/ember-infinity#241]
Hi guys, 

What do you think about putting some examples of testing to readme? I'm not working with the library in my current projects, but I will in the next one and had problems testing in the past.

Looking for the existing tests in the repo I found only tests that are doing scroll in other container besides body. I remember that I needed to scroll down the page body AND the test container body to make it work, is that the right behavior for testing?

Can you guys provide some examples to do tests with ember-infinity?

**Comment by snewcomer** [comment]
@williamweckl It seems I should put together an `ember-twiddle` w/ acceptance tests and update the readme.  I'll do that by the start of next week.

Also we are moving towards a 1-0 [branch](https://github.com/hhff/ember-infinity/tree/1-0), and should be getting that in an alpha release soon.

**Comment by hhff** [comment]
Nice Scott!!
