### ISSUE TITLE
Docs for v1.0.0

### ISSUE THREAD

**Issue by jackiehluo** [ember-infinity/ember-infinity#266]
Are the docs correct for `v1.0.0`? I've tried using the infinity loader component and creating my own load more button, following the docs exactly, and neither works—the initial load of the first page is always fine, but then there are never any subsequent requests made for later pages, and my understanding was that there's nothing more I need to implement beyond adding the route mixin and a component to go with it.

Since it looks like only the alpha supports Ember 3.0, which is what I'm using, I thought the problem might be the documentation?

**Comment by jackiehluo** [comment]
Hm, so I've been debugging, and it looks like my problem may be:

```
{{#each model as |product|}}
  <h1>{{product.name}}</h1>
  <h2>{{product.description}}</h2>
{{/each}}

{{infinity-loader infinityModel=model}}
```

`model` that gets passed into `infinity-loader` in this case is an array, right, since we're iterating over an array of model objects to create list elements? But in the route mixin, we have:

```
this._infinityModels.find(function (model) {
  return model === infinityModel;
});
```

And in this case, `model` is an object that contains all of the `infinityModel` options, which makes sense. But how is `model === infinityModel` ever supposed to be true if what we've passed as `infinityModel` is an array?

Anyway, I assume I'm just misunderstanding what `infinityModel` is supposed to be. Would really appreciate any help!

**Comment by snewcomer** [comment]
Hey @jackiehluo 👋  What does your route look like?  You basically have two options:

1. Are you calling `this.infinityModel(...` from your [route](https://github.com/ember-infinity/ember-infinity#basic-usage) model hook?  By doing so, the `model` in your template is basically a proxy to the underlying content (`ArrayProxy`) with other properties that manage queries to your backend such as `page` and also determine if it should [call](https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js#L103) another action to fetch more data.

2. It is possible to use the `infinity-loader` component without a model, but with a custom action.  But then you won't get all the benefits that this addon!

```
    {{#infinity-loader
      infinityLoad=(action "infinityLoad")
    }}
    ...
```

**Comment by jackiehluo** [comment]
The route looks like:

```
export default Ember.Route.extend(AuthenticatedRouteMixin, InfinityRoute, {
  model() {
    return this.infinityModel("merchant");
  }
});
```

So I think the main difference is just that I have an Ember Simple Auth mixin, but I've tested it without that mixin, and it still doesn't work.

Here's more or less what the template looks like—maybe this part is what's wrong?

```
{{#each merchants as |merchant|}}
  {{merchant.name}}
{{/each}}

{{infinity-loader infinityModel=merchants}}
```

Thanks so much for taking the time to look!

**Comment by snewcomer** [comment]
@jackiehluo Ah looks perfect. I think you are pointing out something pretty important that needs to be improved.  Also, just to make sure, you are on one of the alpha series, correct?

There is one more dependency (if you want to call it that).  And that is `meta.total_pages`.  See [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js#L106) and [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js#L106) and [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js#L78).  Depending on your backend, you can customize the `totalPagesParam` on the infinityModel. Otherwise you can calculate on the frontend.

Does this help?  I definitely think a follow up PR needs to be made to the docs! 👍

**Comment by jackiehluo** [comment]
Yep! I'm on the alpha.

Oh, interesting! I'm not sure I understand what you mean—so I would need to pass `TOTAL_PAGES_PARAM` into the infinity model here? Would that be the number of total pages or the path to making that request to the back-end?

```
export default Ember.Route.extend(AuthenticatedRouteMixin, InfinityRoute, {
  model() {
    return this.infinityModel("merchant", totalPagesParam: TOTAL_PAGES_PARAM);
  }
});
```

**Comment by snewcomer** [comment]
@jackiehluo By default, ember-infinity looks for `meta.total_pages` in the response.  However, if your backend is sending something different back in the response, you can customize like you pasted above.  All passing `totalPagesParams` is doing is setting a property on the `infinity-model`, saying to expect this param in the response.  See links above and this PR #267 and lmk what you think!

So does your server response send back anything including something about how many total pages are in the payload?

**Comment by jackiehluo** [comment]
I'm using the Kaminari gem out of the box, so if that doesn't send total number of pages by default, then the payload doesn't have it—let me check later when I have my work laptop!

But my `infinityModel` that gets passed into the infinity loader looks correct, then? It's fine that `merchants` is an array of merchant objects?

**Comment by snewcomer** [comment]
@jackiehluo Your route model hook, by default, will pass a `model` variable to your controller/template, so actually you need to reference `model` instead of `merchants`, unless you have it aliased in your controller like so: `merchants: alias('model')` or using `setupController`, which I imagine you already do!  This means `merchants` should actually be an instance of `InfinityModel` as shown [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/lib/infinity-model.js) and not a primitive JS array.

Lmk if the Kaminari gem still works out of the box!  (I haven't used it in sooooo long :) ).  Otherwise we should update this lib.

**Comment by jackiehluo** [comment]
Oh, it's literal! I took it to mean "replace `model` with the model from your project," but that makes a lot more sense. Cool, that fixes that problem that I mentioned. Maybe worth explicitly mentioning that in the docs, too? (Happy to submit a PR if that's helpful!)

Kaminari does not appear to send the total number of pages! So I guess that's the problem? The API response is:

```
{
    "merchants": [
        {
            "data": ...
        },
        {
           "data": ...
        }
    ]
}
```

But there's no meta field. Going to try adding that and see how that goes.

**Comment by jackiehluo** [comment]
Ahhh, okay! So—I added the meta field, and now it works perfectly with my "Load More" button! Unfortunately, the provided infinity loader still doesn't work (it loads two pages and then stops), but I can use the custom button, so I'm good.

Thank you so, so, so much for all of the help! Let me know if I can update any more of the documentation, too. I would be happy to help!

**Comment by snewcomer** [comment]
Hm.  It should keep fetching with `{{infinity-loader}}` until there are no other pages to fetch.  Are you in a scrollable container (limited viewport) or are you just scrolling the window?

As you prob already know, `model.reachedInfinity` is a boolean that is set once you have reached the end.

https://github.com/ember-infinity/ember-infinity#use-ember-infinity-with-button

**Comment by jackiehluo** [comment]
No container! Just the window. And yeah, it appears to be setting `model.reachedInfinity` to true prematurely with the infinity loader—I'm not sure why yet.

**Comment by snewcomer** [comment]
@jackiehluo Lmk if you need any more help or ideas or feel like making a PR!  Added this PR based on your comments - #267 

Otherwise if you got it figured out, I'll leave closing this issue to you! 👍

**Comment by jackiehluo** [comment]
Oh, that looks great! Cool, thank you so much—I really appreciate it!
