### ISSUE TITLE
Doesn't work if scroll is not visible 

### ISSUE THREAD

**Issue by AlbertGazizov** [ember-infinity/ember-infinity#275]
Thank's for this addon!
Probably this issue is related to the ember-in-viewport, but I'm not sure. 
The issue is that when I reload page and there are not enough records to fill whole screen (scroll is not visible) then the ember-infinity doesn't load additional records to fill the screen. And as a result if I try to scroll it doesn't load more records.
Any thoughts how to fix it?

**Comment by snewcomer** [comment]
Hey @AlbertGazizov 👋  So the scrollbar is not visible, so how is it possible to scroll?  I think I missed an important detail :) . 

Is it dynamic in that there may be more records (to show a scrollbar) or is the # of records constant?  If so, is [this](https://github.com/DockYard/ember-in-viewport#advanced-usage-options) something that you are looking for?  

You can pass a viewportTolerance to the `infinity-loader` component.  Look forward to hearing more details about what you are looking at!

https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L105
https://github.com/DockYard/ember-in-viewport#advanced-usage-options

**Comment by AlbertGazizov** [comment]
Hi @snewcomer 
Yes, I load records dynamically, the first batch of records doesn't fill entire screen as a result scroll doesn't show. So I need a way to load records until the scrollbar becomes visible or all records are shown.
I've read about viewportTolerance but not sure how can it help me.

**Comment by snewcomer** [comment]
@AlbertGazizov What version are you on of ember-infinity?

**Comment by AlbertGazizov** [comment]
@snewcomer I've installed the recent commit from github

**Comment by snewcomer** [comment]
@AlbertGazizov @davidbilling ok yeah this seems like a problem.  I had originally thought `didEnterViewport` was fired.  Did this change for anybody or was this behavior around before?

**Comment by AlbertGazizov** [comment]
I didn't use previous versions, not sure if it was working before

**Comment by davidbilling** [comment]
@snewcomer I did not have this problem before version 1. I will try to debug this. 
I guess since we don't fill the whole page it does not take into account that it should scroll, even if we have more to load. The check must be on if we have loaded all of the data and intersect... (this is just on top of my head, have not looked into the code)

**Comment by mehrdadrafiee** [comment]
I have the same issue on version 0.2.9 (using bound parameters in `infinityModel`).
I updated to 1.0.0-beta.1, extended `infinityModel` to buildParams() and got rid of Bound Parameters but still cannot make it to work :(
Appreciate any help 🙏 

Here is a gist of the old and new files: https://gist.github.com/mehrdadrafiee/83b62dbfbb7c42578a4495be404dd589

**Comment by snewcomer** [comment]
@davidbilling On first load, is your `infinity-loader` component off screen (or not in viewport)?  I'm seeing `isIntersecting` as true on initial load and even on the second request.  However, it stops there.  Digging into why now.

**Comment by davidbilling** [comment]
@snewcomer I have the same thing. It loads first round and _onIntersection is called and second round loads. But then nothing... My request returns 5 items each.

**Comment by snewcomer** [comment]
This almost sounds like is a recursive solution.  We basically need to keep fetching until the `infinity-loader` is out of the viewport.  Does that sounds like what we need to do @davidbilling?

**Comment by davidbilling** [comment]
@snewcomer Yes, that sounds right in my ears. =)

**Comment by snewcomer** [comment]
Anybody else have any thoughts on a solution?

**Comment by davidbilling** [comment]
@snewcomer Since _loadNextPage thinks a page is fully loaded when backend returns it's set of items (it counts it as a page) it leaves it to the in-viewport to check for intersection. This will not work since what _loadNextPage think is a page is not the same a a visible page. Somehow we must tell _loadNextPage to continue loading until it fills the visible page. 
I have no clue right now how to do this (or if I even think right) ...

**Comment by davidbilling** [comment]
@snewcomer so if we can get in-viewports element (that I think will be the last item) and get the position of it and compare to scrollheight... But I don't think recursive in _loadNextPage will work... hmmm...

**Comment by snewcomer** [comment]
@davidbilling Great idea.  I think it is a combination of recursive + checking the viewport.  However, since `infinity-loader` uses `sendAction`, I think this is blocking until #271 is in.  `sendAction` is a one way street.  What we need is the result of the promise to check + potentially load more pages.  Lmk if you agree.  I'm going to keep working on that branch this weekend.

**Comment by davidbilling** [comment]
@snewcomer I agree! Otherwise we could check the infinity-loader object on page at the end in loadNextPage method. Something like;

__loadNextPage(...){
        ...

        let infinityLoaderElem = document.querySelector('.infinity-loader');
        if(infinityLoaderElem && this._calculateHeight(infinityModel) > infinityLoaderElem.offsetTop){
          // load again
          this._loadNextPage(infinityModel, increment);
        }
        return infinityModel;
}

But check for page height... That would maybe work?

**Comment by davidbilling** [comment]
@snewcomer Actually after quick testing the above seems to work. Just change this._calculateHeight(infinityModel) to window.innerWidth

But if it is a nice way.... I don't know

**Comment by peavers** [comment]
Have also just run into this, can confirm @davidbilling fix does work to resolve this. Looks clean enough to me too. Merge?

**Comment by snewcomer** [comment]
@peavers Yep agreed!  Just need to test out more.  Feel free to put in a PR if anybody would like.  Otherwise, I plan on working on this at the start of next week after #271 gets in (which could help immensely)

**Comment by snewcomer** [comment]
PR for this!  #279 if ppl don't mind trying out/reviewing.  

Again, thanks for everyone's input and testing out fixes.

**Comment by davidbilling** [comment]
@snewcomer It works great! I used it in basic mode (have not converted to closure actions yet). Thanks! =)

**Comment by snewcomer** [comment]
Awesome!  Yeah lmk if you have any feedback/put in an issue on the closure actions work (what works and what doesn't work for you).

**Comment by snewcomer** [comment]
This should be fixed and published under `1.0.0-beta.3`!  Again really appreciate everyone jumping in and tackling.  Lmk if there is any regressions.
