### ISSUE TITLE
Delete records is not reflected on page

### ISSUE THREAD

**Issue by akaravashkin** [ember-infinity/ember-infinity#277]
Hello

Ember: 3.0.0
ember-infinity: 1.0.0-beta.1

I have a list of records displaying by infinityModel. If I perform record.destroyRecord(), it goes away from the store successfully, but does not disappear from the page.
It worked on v0.2.8 but has broken after update.

**Comment by snewcomer** [comment]
@akaravashkin Hey 👋. I'm surprised this worked before, but I could definitely be missing something.  I'm wondering if something has changed in Ember Data as there have been some big changes afoot (esp related to immutability).  I'd have to dig around.

A few questions:

0.  What version of Ember/Ember-Data are you on?
1.  Did you also upgrade your Ember app when you upgraded ember-infinity?

Essentially in v0.2.8 was the route passed the data off to the template.  In the beta version, we do a similar thing by using an `ArrayProxy` to manage the collection.

https://github.com/ember-infinity/ember-infinity/blob/e315cdb343f126989453acbd91ca8743a65e7f9e/addon/mixins/route.js#L322

Look forward to hearing back from you.

**Comment by snewcomer** [comment]
@akaravashkin Also note, there is a big improvement coming here: https://github.com/ember-infinity/ember-infinity/pull/271

Depending on a bit more information, we might have to add a `delete` method or something like that to this PR.

**Comment by akaravashkin** [comment]
@snewcomer , thanks for your response. My environment:
Ember: 3.0.0
Ember Data: 3.0.2
ember-infinity: 1.0.0-beta.1

Yes, I upgraded Ember from 2.13. Then I upgraded ember-infinity too. 
I tried to downgrade infinity to 0.2.8 - delete works properly, but I start to receive other errors.

Now my temporary workaround is using latest infinity and manually remove deleted object from my model array.

**Comment by snewcomer** [comment]
@akaravashkin That is good to know!  So, the real test would be, the app at 3.0 w/ ember-infinity 0.2.8.  However, I think it is an `ember-data` thing, so I think what you did by removing the object is required anyways given the move towards more immutability.  I'll put some documentation in to point this out.

**Comment by snewcomer** [comment]
@akaravashkin 1.0 was released fyi!  I think the collection needs to be manually managed by the end user.  So what you are doing with removeObject seems like the best path forward.  Closing but lmk if you have other questions!
