### ISSUE TITLE
Doesn't keep fetching more on page load if view port is smaller than the window

### ISSUE THREAD

**Issue by peavers** [ember-infinity/ember-infinity#278]
Say I'm returning 5 items per page, when the page first loads `infinity` returns 5, then goes off and gets another 5 as the user still hasn't scrolled and there is room to fill. However `infinity` doesn't keep fetching more until the view port is filled as I'd expect it seems to crash after the second trip. 

How do I go about solving this? I'm not sure if it's a bug or I've just implemented something incorrectly.

**Comment by davidbilling** [comment]
See issue 275, it is the same

**Comment by peavers** [comment]
Apologies I must have missed that, you're correct.

**Comment by snewcomer** [comment]
This should be fixed and published under `1.0.0-beta.3`!
