### ISSUE TITLE
Total page

### ISSUE THREAD

**Issue by madgentos** [ember-infinity/ember-infinity#291]
Hello. My api gives away count-posts

```
"meta": {
"count": "278"
}
```

Please tell me how to be.

**Comment by snewcomer** [comment]
@madgentos I'm not sure that is supported directly at the moment.  I guess we could do the math by taking the `count / perPageParam`.

Seems like that would be a reasonable ask.  Let me see if I can roll it into some of the work related to #284

**Comment by snewcomer** [comment]
@madgentos This should be an option for you after #287 is merged!  Would you mind trying out the branch and letting me know if it works for you?

**Comment by snewcomer** [comment]
@madgentos Would you mind trying out #287 in your project and lmk if it fixes your issue!
