### ISSUE TITLE
InfinityModel options changing other InfinityModels options already loaded

### ISSUE THREAD

**Issue by williamweckl** [ember-infinity/ember-infinity#295]
## Problems

- I have two InfinityModels loaded at the same screen and I need those two to call different actions at different Stores. The first load goes well, but the next ones go to the last excecuted InfinityModel configuration.
- With the new infinity service I need to use custom stores to do nested promises queries.

## Context

I've recently updated from `alpha 9` to `beta 6` version, and noticed that I cannot override some previously existent functions. Had to use custom stores for that, but this custom stores configurations are conflicting each other.

My Ember version: 3.0

## My use case

I need to do some nested promise queries to prevent N+1 API queries.

Example: If I load user activities, my API returns the activities with the user ID. When I need to show user info at activity, to each activity Ember will do a request to get the user data. When I do the first query I need to do another to get all the related users together, doing 2 queried instead N+1. I need InfinityModel to wait for the second query before updating model.

I used to do that overriding some route mixin functions, like `_requestNextPage()`;

## To simulate

- Two infinity models at the same route with different options like `store` and `storeFindMethod` configured. Scroll one than the other. Both will call the same store, the last configured.

---------
I honestly don't know the motivation of the change to use infinity service, with the logic inside route mixin besides the above scenarios working great we had the option to override some custom behaviors.

**Comment by snewcomer** [comment]
This is a great point you bring up.  Perhaps this might be a good use case to store the references to the store and find method on the infinity model to allow multiple infinity models to use different store find methods.  @hhff What do you think?

**Comment by snewcomer** [comment]
@williamweckl Could you take a look at #296.  If you do try it out, it might have a diff API (remove the Route mixin, add the service to the route and the model hook looks like `this.infinity.model(...`, so be forewarned (not sure where your code is at) :)  But in any case, if this solve your problem, we might be able to get 1.0 released in the next few days!

It was a great catch you made and one frankly I had yet to think of.  So thank you!

**Comment by snewcomer** [comment]
@williamweckl This should be fixed on master!
