### ISSUE TITLE
afterInfinityModel not working with infinity service

### ISSUE THREAD

**Issue by wuron** [ember-infinity/ember-infinity#298]
Basically title. If you use ember-infinity as service, `afterInfinityModel` is never called.

Root of the problem is that ember-infinity tries to use service to manage different models, but still tries to use instance methods from route (I assume that's legacy from previous versions when mixin was the only way), while not having any access to route. I found the place in code where method should be set: https://github.com/ember-infinity/ember-infinity/blob/master/addon/services/infinity.js#L193
but it actually does nothing, it's basically says `this.afterInfinityModel = this.afterInfinityModel;` which is `undefined`.

**Comment by snewcomer** [comment]
Hm.  Yeah I'm wondering if we need to move that to the `Extended Infinity Model`...Any other thoughts?

**Comment by wuron** [comment]
Hey, I've checked the branch it works great. :+1:
