### ISSUE TITLE
Accessing `this` from within the `infinityModelLoaded()` method

### ISSUE THREAD

**Issue by extremesonic** [ember-infinity/ember-infinity#300]
Hi!

I am learning ember. Help for using your plugin is much appreciated. It's a quick question.

Inside the `infinityModelLoaded()` method, `this` refers to something else (the infinity service?) than I am used to. I want to write the state (loaded/not-loaded) to a service. How can I access a service with `this.get("myService")` from within the `infinityModelLoaded()` method?

Thank you.

**Comment by snewcomer** [comment]
@extremesonic Hi!  👋  I updated the README based on your comments.  It definitely needed to be improved.  So thank you for bringing it up.  You need to essentially pull it off the route and pass to the extended infinity model like so

```
export default Route.extend({
  myService: inject(),

  model() {
    return this.infinity.model('post', {}, ExtendedInfinityModel.extend({ myService: this.myService });
  }
});
```

Then you will have access to `this` service in the event hooks.  Lmk if you have any other questions!

https://github.com/ember-infinity/ember-infinity#model-event-hooks

**Comment by extremesonic** [comment]
Thank you!
