### ISSUE TITLE
Test failing when calling infinity model in page component

### ISSUE THREAD

**Issue by aonawale** [ember-infinity/ember-infinity#304]
My tests started failing with this error message after updating to v1.0 and moving the model loading code to my page component.

```Uncaught Error: Assertion Failed: Cannot deregister unknown unregistered renderer```

```
page-component.js

_isLoading: readOnly('_modelTask.isRunning'),
_infinityModel: readOnly('_modelTask.lastSuccessful.value'),

_modelTask: task(function* () {
    return yield get(this, 'infinity').model('my-model', {
      perPage: get(this, '_itemsPerPage'),
      startingPage: get(this, '_currentPage'),
      pageParam: 'page',
      perPageParam: 'page_size',
      totalPagesParam: 'meta.totalPages'
    });
  }).on('init'),
```

**Comment by snewcomer** [comment]
@aonawale 👋 A few questions if you don't mind.  Does your prod code work?  is your failing test an acceptance test?  Mind adding the test to the issue description when you get time?

**Comment by snewcomer** [comment]
@aonawale I think `1.1.2` should work well for you!  Lmk if you see anything different.

**Comment by aonawale** [comment]
@snewcomer I'm closing this issue because I couldn't reproduce it on another project using the same architecture.

**Comment by snewcomer** [comment]
I think it is fixed on master!  Good it is resolved
