### ISSUE TITLE
Feature Request: Remove requirement for response to contain meta about total pages or count

### ISSUE THREAD

**Issue by snewcomer** [ember-infinity/ember-infinity#306]
One improvement (as brought up in #305) is to allow `ember-infinity` to work even if the response does not contain information about total pages or count.  We have two options:

1. default total pages to Infinity instead of 0

2. add API item for users to specify, per route, their responses do not contain any meta data.

This effectively would cause user's `infinity-loader` to continually fetching (or trying to fetch) new records.  This might be an acceptable change to the library in cases where the user's table does not show a loading spinner.  Moreover, our use of [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) doesn't hurt performance of your page due to it's asynchronous nature.

Let me know your thoughts!

**Comment by johncalvinyoung** [comment]
Additionally, if you manually manage canLoadMore, then you can stop the infinitely loading loader.

**Comment by nickschot** [comment]
In a JSONAPI situation you can of course also use the info from "links" (e.g. `next` or `last`) if present. This would also be possible with the manual management of canLoadMore.
