### ISSUE TITLE
Replace ember-in-viewport with ember-spaniel

### ISSUE THREAD

**Issue by snewcomer** [ember-infinity/ember-infinity#309]
Since ember-spaniel is now at 1.0 (IntersectionObserver + polyfill), we can look at replacing ember-in-viewport.

https://github.com/asakusuma/ember-spaniel

**Comment by snewcomer** [comment]
I think there is some basic features missing in ember spaniel, including isIntersecting and continuous observing an element.

**Comment by nickschot** [comment]
@snewcomer there is the `watcher`: https://github.com/asakusuma/ember-spaniel#getwatcher . Not sure about isIntersecting.

Was the reason for considering a replacement that it's a more lighter/native solution than in-viewport?

**Comment by snewcomer** [comment]
@nickschot With our static [administrator](https://github.com/DockYard/ember-in-viewport/blob/master/addon/services/-observer-admin.js) managing native Intersection Observers in ember-in-viewport, we have a super performant solution up there now.  I plan on doing a post on performance differences between no administrator vs current solution.  Just have to find some time :)

**Comment by nickschot** [comment]
No hurry, I was just wondering why you were considering the change :)
