### ISSUE TITLE
It does not display the second page

### ISSUE THREAD

**Issue by rodrigoyoshida** [ember-infinity/ember-infinity#310]
For some reason the infinity-loader does not display the content from the second page. It loads and displays the first page, requests the content from the endpoint, the model gets updated (I can see it by checking its length in the view, also the inspector shows me it successfully returned the new data) but the infinity-loader only displays the content from the first page, being stuck with the loading text defined in the view.

My API is a little different than usual. I have a random page number and can't send the standard params to avoid wrong behavior on my API, that's why I had to delete it from the params object. 

``` js
const ExtendedInfinityModel = InfinityModel.extend({
  buildParams() {
    let params = this._super(...arguments);
    params["page[number]"] = this.get('nextPage');
    delete params.page;
    delete params.per_page;
    return params;
  },

  afterInfinityModel(chats) {
    this.set('canLoadMore', chats.get('length') > 0);
    this.set('nextPage', chats.get('meta.paginate.next.number'));
  },
});

model(params) {
    return RSVP.hash({
      chats: this.infinity.model(
        "chat", 
        { "page[limit]": 6 }, 
        ExtendedInfinityModel
      )
    });
  }
```

``` hbs
{{infinity-loader
  scrollable="#inbox-list-items"
  infinityModel=model.chats
  loadingText='Carregando...'
  loadedText='Todos os itens carregados.'
}}
```

**Comment by snewcomer** [comment]
@rodrigoyoshida Hey!  Nice work with the Extended Infinity Model.  👋  A few thoughts so we can keep the conversation going:

1.  The infinity-loader is only responsible to fetching new items when it is in viewport.  The actual display of those items happens above the loader in something like `{{#each chats as |chat|}}` as I'm sure you already aware.

2.  In your response above, were you saying it was successfully making the second request (based on the network request)?

**Comment by rodrigoyoshida** [comment]
I suspect that it could be related to the fact that my API does not return the total_pages meta property, since this problem only occurs on the second time it tries to fetch the data.

**Comment by rodrigoyoshida** [comment]
@snewcomer I finally solved the problem! I made several changes and then suddenly it started working, but I suspect one of the problems is related to a bug I was able to reproduce. Whenever I used the scrollable attribute it only fetched twice, the third time did not work. Also changed the way I manipulate the perPage and page params, previously I was deleting them on the buildParams step, but now I am doing like the code below, it might have helped. 

``` js
import Route from '@ember/routing/route';
import InfinityModel from 'ember-infinity/lib/infinity-model';
import { inject as service } from '@ember/service';

const ExtendedInfinityModel = InfinityModel.extend({
  buildParams() {
    let params = this._super(...arguments);
    params["page[number]"] = this.get('nextPage');
    return params;
  },

  afterInfinityModel(chats) {
    this.set('canLoadMore', chats.get('length') > 0);
    this.set('nextPage', chats.get('meta.paginate.next.number'));
  }
});

export default Route.extend({
  infinity: service(),

  model() {
    return this.infinity.model("chat", {
      "perPage": 6,
      "perPageParam": "page[limit]",
      "pageParam": "page[number]"
    }, ExtendedInfinityModel);
  }
});
```
This is the working code:
``` hbs
<p style="text-align: center">Quantity: {{model.length}}</p>

<div id="scrollablecontent" style="width: 300px; height: 300px; margin: 0 auto; padding: 10px; border: 1px solid blue; overflow-y: auto;">
  <h2>Chats container</h2>
  <div>
    {{#each model as |chat|}}
      <p style="padding: 10px; border: 1px solid red">{{chat.name}}</p>
    {{/each}}
    {{infinity-loader infinityModel=model}}
  </div>
</div>
```
But if I change the infinity loader code like below it only fetches twice.
``` hbs
{{infinity-loader scrollable="#scrollablecontent" infinityModel=model}}
```
Also in the docs it tells me to use the model passed as an argument to change the canLoadMore attribute, but it did not work here, I had to use "this" instead.
``` js
  afterInfinityModel(posts) {
    let loadedAny = posts.get('length') > 0;
    posts.set('canLoadMore', loadedAny);
```
Hope I was able to help!

**Comment by snewcomer** [comment]
@rodrigoyoshida Great!  Nice work and awesome examples.

So awesome I added it to the dummy app and tested it.  It is somewhat similar to your example.  But it does show that I can scroll to the end of the list multiple times in the acceptance test with the scrollable, but only after the fix in the below PR.  So THANK YOU for that!  

Also updated the README with `this.set`.  Lifesaver 👍 

https://github.com/ember-infinity/ember-infinity/pull/312/files#diff-f5ee7e4b668b1e7c566e79dbe3a57120R6

**Comment by rodrigoyoshida** [comment]
I am happy to see I was able to help you improve the addon! By the way, it is really awesome! We use it a lot here and we are really happy that it has a great support. Good job!

**Comment by snewcomer** [comment]
Closing for now.  Let me know if there is anything else you see!  🎉  Thanks again.
