### ISSUE TITLE
Infinity-loader not hiding when there's just a single page

### ISSUE THREAD

**Issue by nickschot** [ember-infinity/ember-infinity#311]
I have passed `hideOnInfinity=true`. When there is just a single page returned, the infinity-loader will still show with the default text of: `Infinite Model Entirely Loaded.`. It does have the `reached-infinity` class applied. When it needs to do a query after the initial one (be it a model reload or another page) it will hide it correctly.

**Comment by snewcomer** [comment]
@nickschot Oh wow you are right.  Great catch!  Will put up a fix at the end of the day unless you have time for a PR!

**Comment by nickschot** [comment]
I was going crazy about this one haha, thought it was my API at first. Unfortunately I don't have any time in the next few hours.

**Comment by nickschot** [comment]
After a quick look it seems to just be the observer not firing after/on init.
