### ISSUE TITLE
Regression, non-blocking model support and initial page of results not hiding infinityLoader

### ISSUE THREAD

**Issue by Duder-onomy** [ember-infinity/ember-infinity#313]
Hey, 

Found an issue with the latest version 1.1.2
Seems that if using a non blocking model hook + hideOnInfinity and there is only one page of results, never seems to hide the infinity loader. 

[Here is a commit](https://github.com/Duder-onomy/ember-infinity/commit/b88015b900b436441532ea3aca0ea164aca7ac24) I made on my fork to demonstrate the issue, had to hack in some extra param support to the mirage serializer.

If you pull that commit in, you will see that the infinityLoader never drops. 
![image](https://user-images.githubusercontent.com/1612785/43864786-8418712a-9b15-11e8-89ea-5aa35eabc77b.png)

Debugging this, it seems like the observer added [here](https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L106) does not seem to observe through the promise proxy of the non-blocking model.

I thought about something like this:
```
didInsertElement() {
    this._super(...arguments);

    this._loadStatusDidChange();
    this.addObserver('infinityModelContent.reachedInfinity', this, this._loadStatusDidChange);
    this.addObserver('hideOnInfinity', this, this._loadStatusDidChange);

    // Wait for the infinity model THEN trigger the load status...
    get(this, 'infinityModelContent').then(() => this._loadStatusDidChange());

    let scrollableArea = get(this, 'scrollable');
    let infinityModel = get(this, 'infinityModelContent');
    if (infinityModel) {
      set(infinityModel, '_scrollable', scrollableArea);
    }
  },
```
That does not work ^.

Please let me know if there is anything I can do to help. 

If you know the cause and can pseudo code it to me I don't mind adding failing tests and PR'ing. Just a little confused on what is happening under le hood.

**Comment by snewcomer** [comment]
@Duder-onomy 👋. Great catch! 👍   I believe I made a mistake.  Here we are observing on didInsertElement.  HOwever, at this point in the lifecycle, it is a promise.  In the previous [solution](
https://github.com/ember-infinity/ember-infinity/commit/c71381ba534c3652b547187715d904cdc15f8e92#diff-5b074f72f77f5bb4e2eaf2e974dd10edR106), it was able to observe the resolved value.  So I think there is a slight difference in those two approaches.  When we are checking state (`reachedInfinity` and such, we need to wait for the promise to resolve before asking the questions such as [this](https://github.com/ember-infinity/ember-infinity/commit/c71381ba534c3652b547187715d904cdc15f8e92#diff-5b074f72f77f5bb4e2eaf2e974dd10edR161)

So we either revert to the old approach and try to solve hide on first load or we come up with a diff solution.

Does this make sense?

**Comment by Duder-onomy** [comment]
I am starting to understand what is going on . 

These are the minimal changes i needed to make to get it working for me in my use case... but a bunch of other tests are failing: https://github.com/Duder-onomy/ember-infinity/commit/1252d384e39013f9c702f9fb037fed299163c06e

I will spend some more time right now. Getting closer.

**Comment by Duder-onomy** [comment]
Aight, spent another few mins on this one today.
It seems to me that we should just always treat the infinityModel as a promise. This way any use case will be covered. 

Change the will insert element hook:
```
  willInsertElement() {
    let ObjectPromiseProxy = ObjectProxy.extend(PromiseProxyMixin);
    let proxy = ObjectPromiseProxy.create({
      promise: resolve(get(this, 'infinityModel')),
    });

    set(this, 'infinityModelContent', proxy);
  },
```

Then all accessors use the then-able:
```
_loadStatusDidChange() {
    get(this, 'infinityModelContent')
      .then(() => {
        if (get(this, 'infinityModelContent.reachedInfinity') && get(this, 'hideOnInfinity')) {
          set(this, 'isVisible', false);
        }
      });
  },
```

This commit, https://github.com/Duder-onomy/ember-infinity/commit/76ac0280faea04155a65e16b7530e82a3e843bf3?diff=split seems to fix everything.

I went through all the example routes in the dummy repo, and everything seems to work as expected. 
The tests, however, are mostly failing.

**Comment by snewcomer** [comment]
@Duder-onomy Would you like to put up a PR for the work you did?  I can help if you are strapped for time 🙌

**Comment by Duder-onomy** [comment]
Honestly, you can probably fix is allot faster than I can. 
I was just trying to poke at it and see if it was easy. 

I think I understand everything that is happening except the loadPrevious parts of the code. 

But yeah, if you take a stab at it, shoot me a message and I will pull it into TheDyrt and see if it fixes the issue.
