### ISSUE TITLE
`isDoneLoading` doesn't update if infinityModel is changed

### ISSUE THREAD

**Issue by ryedeer** [ember-infinity/ember-infinity#331]
Hello! I've found a problem with the `infinity-loader` component: if the `infinityModel` changes without re-rendering the component, the `isDoneLoading` property does not update properly.

The use case: in our application, we have a route that displays a data table and has some filter buttons that change the query parameters. If we click one of the filter buttons, Ember loads the new data and creates a new instance of infinity model, but only the data on the page are re-rendered, while the `infinity-loader` component stays intact. As the result, the `infinityModelLoaded` callbacks stop working because they're hooked to the first infinity model, and the loader doesn't hide after loading all the data in the new query (or doesn't show if the infinity was reached by the first query).

I think that a possible solution may consist of creating an observer for the `infinityModel` property and adding the `infinityModelLoaded` callbacks again each time the model is changed. (Actually, I tried it by patching the code, and it seems to work just fine.)

P.S. I saw the closed issue #323 that looks very similar, but it seems that the problem lies within Infinity (at least, in the case I've described above).

**Comment by snewcomer** [comment]
@ryedeer 👋 Hey Oleg!  What version are you on?  

Also do you think you could share some of your code?  A few preliminary questions to help debug:

0. Are you appending records or does the new data include the records previously?
1.  What does the filter JS logic look like?  Is it on a controller or component?
2.  What does your hbs infinity-loader logic look like?
3.  Are you using any Service API [methods](https://github.com/ember-infinity/ember-infinity#service-methods)?

**Comment by ryedeer** [comment]
We currently use Ember 3.5 and ember-infinity 1.2.3.

0 and 1: When the new set of data is loaded, a new instance of the model is created. The filter logic is implemented in the route/controller; the filter buttons are actually changing the query params, so the model is refreshed. However, after the refresh, Ember only re-renders the part of the page with the actual data, but not with the `infinity-loader` component, so `willInsertElement`/`willDestroyElement` hooks in the component aren't fired on the second and later refreshes.

The code looks similar to this (we have many more query params in the actual code, but I think it doesn't matter in this case):


```javascript
export default Route.extend({
  queryParams: {
    by_dealership: {
      refreshModel: true
    }
  },

  model(params) {
    return this.infinity.model('stock', params);
  }
});
```

```javascript
export default Controller.extend({
  queryParams: ['by_dealership'],
  by_dealership: null
});
```

2. The hbs pretty straighforward:

```hbs
{{#infinity-loader infinityModel=model}}
  <div class="spinner"></div>
{{/infinity-loader}}
```

(The spinner hides when infinity-loader has the `reached-infinity` class.)

3. We don't use the service methods in this route.

Also, as a temporary solution for this problem, I've created the monkey patch in our application, and it seems to fix the aforementioned behaviour:

```javascript
import InfinityLoaderComponent from 'ember-infinity/components/infinity-loader';
import { get, set, computed, defineProperty } from '@ember/object';
import { resolve } from 'rsvp';

export default InfinityLoaderComponent.reopen({
  observeModel() {
    get(this, 'infinityModelContent')
      .then((infinityModel) => {
        infinityModel.on('infinityModelLoaded', this, this._loadStatusDidChange);
        set(infinityModel, '_scrollable', get(this, 'scrollable'));
      });  
  },

  willInsertElement() {
    defineProperty(this, 'infinityModelContent', computed('infinityModel', function() {
      return resolve(get(this, 'infinityModel'));
    }));
    this.addObserver('infinityModel', this, this.observeModel);
  }
})
```
