### ISSUE TITLE
document.documentElement does not represent the scrollable root in all browsers

### ISSUE THREAD

**Issue by johncalvinyoung** [ember-infinity/ember-infinity#333]
Safari 11 (among others, possibly) scrolls `document.body` by default, not `document.documentElement`. Therefore https://github.com/ember-infinity/ember-infinity/blob/master/addon/services/infinity.js#L299 is selecting something that in some browsers cannot be scrolled by setting `scrollTop` on https://github.com/ember-infinity/ember-infinity/blob/master/addon/services/infinity.js#L346.

Solution: sniff browser, or use `window.scrollTo(x,y)` when `_scrollable` is not set.

**Comment by snewcomer** [comment]
@johncalvinyoung Oh you are so right!

For the ternary, what do you think about -

```
: document.scrollingElement || document.documentElement;
```

e.g. This would return body for Safari and  html for Chrome; IE would be covered by document.documentElement since scrollingElement is not supported.

**Comment by johncalvinyoung** [comment]
HMM! Somehow I didn't know about `document.scrollingElement`. That's a much nicer fix. :+1:

**Comment by snewcomer** [comment]
Learn something new everyday!  @johncalvinyoung 1.2.6 was deployed.  Thanks a ton for your work!
