### ISSUE TITLE
InfinityLoader visibility does not reset when InfinityModel changes

### ISSUE THREAD

**Issue by maprules1000** [ember-infinity/ember-infinity#339]
So I've got this route. It's a pretty great route. It uses a standard model hook. And it loads several models, including an infinity model. Nothing crazy. 

I can navigate to other routes that will reload the infinity model with new and different data. It's great and it works like a charm. However, once the infinity loader (using `hideOnInfinity`) disappears, it does not come back when a new infinity model is loaded.

I've dug into the `ember-infinity` code and come up with a solution.  I've added this small bit of code in `infinity-loader.js`.
```
didUpdateAttrs() {
  set(this, 'isVisible', true);

  this._loadStatusDidChange();
},
```

This resets the `infinity-loader` visibility whenever the infinity model changes. When testing, the `didUpdateAttrs` hook looked to be the best one to use since it only fired when the passed in infinity model changed, and triggers the `_loadStatusDidChange` to fire again (since the load status could have changed with the new dataz).

Interestingly, it looks like there isn't currently anything that actually resets the `isVisible` property of the `infinity-loader` component.

I plan on opening up a PR later today to introduce the changes above.

p.s. I have checked out #313 and #331 and it looks like this issue is different. Can also confirm that I'm on v1.2.6.

**Comment by leimig** [comment]
I found the same issue. +1

**Comment by adambedford** [comment]
I'm having the same issue

**Comment by snewcomer** [comment]
Well sounds like something we neee to fix!

**Comment by snewcomer** [comment]
@maprules1000 Ya I think you found a bug!  So we use `addObserver` in a few spots as it allows you to watch specific things instead of all the things.  This has become especially important as Glimmer has tried to do as little work as possible on page transitions and re-render.  Lmk what you think about this PR! https://github.com/ember-infinity/ember-infinity/pull/371
