### ISSUE TITLE
Use ember-infinity with button

### ISSUE THREAD

**Issue by zion03** [ember-infinity/ember-infinity#352]
I'm trying to implement component with button as described in docs: https://github.com/ember-infinity/ember-infinity#use-ember-infinity-with-button
Variant as mentions in docs doesn't work 
`Nothing handled the action 'infinityLoad'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.`
So I missed some details or example not working.
Found solution like 
```
click: function(){
this.get('infinityModel').then((im) => {
     this.infinity.infinityLoad(im);
    });
}
```

**Comment by snewcomer** [comment]
@zion03 YOu are right!  #353 should update the old docs.  Thanks a lot.  lmk if you have any other questions/thoughts!

**Comment by alexparker** [comment]
This came up with me because of the async nature of the infinityModel. I ended up having to do this:
```
  @action
  async loadMore() {
    let model = await this.get('infinityModel');
    this.infinity.infinityLoad(model);
  }
```
I'm on Ember 3.13 - Does the example in the docs work exactly as is for you?
