### ISSUE TITLE
Output of blueprint should be like default component template

### ISSUE THREAD

**Issue by benmurden** [ember-infinity/ember-infinity#358]
The output of `ember g infinity-template` is currently the following.

```handlebars
{{#if hasBlock}}
  {{yield infinityModelContent}}
{{else}}
  {{#if infinityModelContent.reachedInfinity}}
    <span>{{loadedText}}</span>
  {{else}}
    <span>{{loadingText}}</span>
  {{/if}}
{{/if}}
```

But this does not appear to work; the status message does not update. The default template uses `isDoneLoading` instead of `infinityModelContent.reachedInfinity` and works as expected.

```handlebars
{{#if hasBlock}}
  {{yield infinityModelContent}}
{{else}}
  {{#if isDoneLoading}}
    <span>{{loadedText}}</span>
  {{else}}
    <span>{{loadingText}}</span>
  {{/if}}
{{/if}}
```

Should the output of the blueprint not mirror the default template? Perhaps there is something I'm missing.

**Comment by snewcomer** [comment]
@benmurden You are likely right. Would happily accept a PR to fix!  Thanks for reporting 👍
