### ISSUE TITLE
options.store with circular references causes exception

### ISSUE THREAD

**Issue by artinboghosian** [ember-infinity/ember-infinity#360]
We are using Ember 3.7 at the moment and recently upgraded from 1.0.0 to 1.3.2. This behavior did not exist in 1.0.0 and was only introduced after the upgrade.

If you pass in a custom store into options: `this.model.infinity('model-name', { store: this.store })` you will get an exception `Maximum call stack size exceeded`. This is because the store has at least one property that has circular reference to itself, the `defaultAdapter` property. When generating a unique identifier using `stringifyObjectValues` you will essentially get into an infinite recursive call because of this circular reference. This is because the method recursively calls itself if the value of an option is `typeof` object (which the DS.Store is). So essentially you get to the store key which returns the store which has a key defaultAdapter that is also an object and has a key of store (and essentially you go store, defaultAdapter, store, defaultAdapter, store, defaultAdapter and on until call stack gets too big).

I know you don't need to pass this.store as it is the default I was only using it as an example. We are using HasManyQueryMixin which adds query method to has many relationships so that we can query relationships through parent model. So in our actual case we are passing the model as the store (I'm assuming Ember.Model also has some store of circular reference as one or more of it's properties).

Looks like this was introduced in https://github.com/ember-infinity/ember-infinity/commit/22bdd0578ffaa109189e061613d1fa8f3dbf0e06

Not sure what the best course of action is, clearly the purpose of the commit make sense (to include nested params in the unique identifier). Is the store relevant to generating a unique identifier for a request (e.g. can it be ignored)? Seems like it might be relevant if you were querying same model with same params but different store for some reason (but i'm not sure)? Maybe the store key needs to be treated specially in the stringifyObjectValues method, but that still leaves the problem of having other options that might have circular references breaking the code.

**Comment by snewcomer** [comment]
👋 @artinboghosian So 1.3.1 works for you? I think we could leave out the store from this.  Perhaps only target certain "types" of options.

**Comment by artinboghosian** [comment]
@snewcomer I haven't tested 1.3.1 but i'd assume prior to that change it would have worked fine since there was no recursive call. I think if we could limit to specific types it would be fine. The built in `typeof` returns `object` for Javascript Objects as well as Ember objects, maybe we could take advantage of `Ember.typeOf` which seems to return `instance` for Ember.Objects and `object` for Javascript objects?

**Comment by snewcomer** [comment]
@artinboghosian Got this ready for your review https://github.com/ember-infinity/ember-infinity/pull/361
