### ISSUE TITLE
`infinityModel.on is not a function` error - using infinity-loader within power-select/options

### ISSUE THREAD

**Issue by Aaronfischer** [ember-infinity/ember-infinity#363]
Hello!

I'm attempting to setup an "infinite scroll" within ember-power-select. I've got a similar setup to the docs:
```hbs
{{!-- /components/power-select/options --}}
{{#each options as |opt index|}}
  {{#if (ember-power-select-is-group opt)}}
    {{yield option select}}
  {{/if}}
{{/each}}
{{infinity-loader infinityModel=options}}
```

Then on the controller:
```js
// app/controllers/foo/input
listContent: computed(function () {
  return this.infinity.model('list', {
    perPage: 2,
    perPageParam: 'page[limit]',
    pageParam: 'page[offset]',
    totalPagesParam: 'meta.total',

    'filter[is-archived]': false,
    sort: 'label',
  });
}),
```

Then when I open up power-select and the options are displayed, an error is thrown: `infinityModel.on is not a function at Ember.get.then.infinityModel (infinity-loader.js:169)`.
Could you provide any insight into why this could happening? 
Perhaps I missed something in the config? (It does fire the initial request to populate just fine)

**Comment by nickschot** [comment]
Is options a reference to listContent (the infinity model)? (It should be)

**Comment by snewcomer** [comment]
@Aaronfischer What version are you on?  Also, presumably, this [line](https://github.com/ember-infinity/ember-infinity/blob/5a258376499f51a5c3c0cc5e67492f179304ac20/addon/components/infinity-loader.js#L98) was called.  

Like Nick said, is `options` an instance created [here](https://github.com/ember-infinity/ember-infinity/blob/5a258376499f51a5c3c0cc5e67492f179304ac20/addon/services/infinity.js#L246)

**Comment by Aaronfischer** [comment]
@nickschot / @snewcomer That was it. 👍Didn't occur to me that power-select manipulated the passed in `options`, but it does. 
Thanks!
