### ISSUE TITLE
Scroll up to load next page

### ISSUE THREAD

**Issue by adambedford** [ember-infinity/ember-infinity#368]
I'm building a chat feature and I'd like users to be able to scroll up to see older messages (think iMessage, WhatsApp, any messaging app). Is that possible with this library and putting the loader component above the collection? The next pages would have to be added to the collection before the current pages to maintain the order of oldest to newest messages.

To complicate things further, I'm also planning to make periodic requests to the server to fetch new messages in a conversation and will need to add them to the collection.

Is any/all of the above possible? Any guidance would be greatly appreciated!

**Comment by snewcomer** [comment]
Yep!  There is a loadPrevious section [here](https://github.com/ember-infinity/ember-infinity#infinity-loader).  Lmk if you have troubles implementing.

**Comment by adambedford** [comment]
Thanks for the response @snewcomer. I've been understanding the docs in this way: the `loadPrevious` flag would decrement the page count and prepend that to the collected. In a conversation view of a message thread, I'm thinking that page 1 will be the bottom-most page, and scrolling up will load pages 2, 3 etc. So the infinite scroll is basically upside-down

**Comment by snewcomer** [comment]
Oh right.  Yeah this might need some help to get it to work since I think we are checking how close the sentinel is to the bottom of the viewport.  I'm open to figuring this out ASAP though.

https://github.com/ember-infinity/ember-infinity/blob/master/addon/components/infinity-loader.js#L255

**Comment by adambedford** [comment]
Thanks for your response Scott. I appreciate your willingness to work with me on this.

I ended going for the `flex-direction: column-reverse;` approach, which means my markup, and ember-infinity code, works as normal, but the browser reverses it. This has the nice advantage of always scrolling to the 'bottom' of the message list when entering the route.
