### ISSUE TITLE
Catching Errors is not working as expected in 1.3.3

### ISSUE THREAD

**Issue by tomoguisuru** [ember-infinity/ember-infinity#369]
After updating from 1.2.7 to 1.3.3 I found that the addon is no longer throwing the adapter errors as it was previously and is instead returning the following:

`Assertion Failed: ArrayProxy expects an Array or Ember.ArrayProxy, but you passed boolean`

_retrieval code_
```js
task__loadProfiles: task(function* () {
  const profiles = yield get(this, 'infinity')
    .model('profile', this._queryParams())
    .catch(e => {
      this.send('error', e);
    });

  set(this, 'infinityModel', profiles);
}),
```

_testing with a 401 Response_
```js
server.get('profiles', { message: 'Unauthorized' }, 401);
await visit('/profiles');
assert.equal(currentRouteName(), 'errors.unauthorized', 'Redirects to unauthorized page');
```

_testing with a 403 Response_
```js
server.get('profiles', { message: 'Forbidden' }, 403);
await visit('/profiles');
assert.equal(currentRouteName(), 'errors.forbidden', 'Redirects to forbidden page');
```

**Comment by snewcomer** [comment]
@tomoguisuru Did this involve also upgrading other deps (ember-source, etc) or simply scoped to ember-infinity update?

**Comment by tomoguisuru** [comment]
@snewcomer this happened only with the `ember-infinity` update. Rolling back to 1.2.7 resolved the issue

**Comment by nickschot** [comment]
I am also seeing this on 1.3.4

**Comment by kylefredin** [comment]
I ran into this same issue (endpoint returning 40x error) using version 1.3.3. Downgrading to 1.2.7 resolved the issue for me. 

Ember 2.18.2
Ember Data 2.81.2

**Comment by snewcomer** [comment]
@tomoguisuru Hi all!  Would somebody mind reviewing this PR when they have time?  Sorry about the inconvenience!

https://github.com/ember-infinity/ember-infinity/pull/374

**Comment by kylefredin** [comment]
Hi @snewcomer that looks good to me, thank you so much!

**Comment by snewcomer** [comment]
1.4.2 published!  THank you all!
