### ISSUE TITLE
loading-animation on first load

### ISSUE THREAD

**Issue by MatthewPardini** [ember-infinity/ember-infinity#370]
I've got a "loading-animation" (circle spinner) that I show when infinity-loader is loading more data. However, on the first retrieval of data, the spinner does not show. I would like it to.

My template looks like this:

`	{{#infinity-loader infinityModel=model isDoneLoading=isDoneLoading}}
		{{#unless isDoneLoading}}
			<span>{{loading-animation}}</span>
		{{/unless}}
	{{/infinity-loader}}
`

When I click my search button that triggers an action, I want to display the spinner. Am I doing this wrong or is this something that cannot be done using isDoneLoading?

**Comment by snewcomer** [comment]
@MatthewPardini So you want it to show when the page first loads, is that right?  fyi i'll be doing some work on that tomorrow to fix some outstanding issues #339

**Comment by MatthewPardini** [comment]
The data load is triggered by a button click and action. So I want it to show in the time period between the click and when “isDoneLoading” getting set to true, as it’s a “loading” icon. I think that’s what you meant, just being clear

**Comment by snewcomer** [comment]
@MatthewPardini `loadingMore` is not public.  So you could try that!

**Comment by MatthewPardini** [comment]
I ended up working around it, but may have to implement this again down the road and will try then.
