### ISSUE TITLE
How to retrieve a JSON data?

### ISSUE THREAD

**Issue by vinayak01** [ember-infinity/ember-infinity#373]
I'm getting the data from "http://example.com/people.json". The response data will be
`{
  people: [
    {
      name: 'Andrew Thomson',
      age: 32
    },
    {
      name: 'Callum Falconer',
      age: 28
    },
    {
      name: 'Evelia',
      age: 26
    }
  ],
  'meta': {
    'total': 20,
    'total_pages': 2,
    'page': 1
  }
}`

I need to iterate this response using ember-infinity. How do I make this work with ember-infinity?

**Comment by snewcomer** [comment]
ember-infinity works with ember data or your own custom store that has `find`, `findAll` or your own custom versions of retrieving data.  Also, ember-infinity does not deal with iterating data.  We only notify when to load the data based on the distance of the `infinity-loader` component from, say the bottom of the viewport, and then actually take care of requesting from your backend when the time is right.  We don't, for example, deal with `list item`s.

```
<-- top of viewport -->
- list item
- list item
- list item
<-- bottom of viewport -->
`{{infinity-loader}}`
```

**Comment by vinayak01** [comment]
So ember-infinity requires model instance to retrieving the data. It does not deal with the plain hash.

**Comment by snewcomer** [comment]
What matters is how your "store" (the service that will request the data from the backend) is implemented and if it works with ember-infinity.  ember-infinity allows you to build lists of items that infinitely scroll.  We default to assume you are working with ember-data, but you don't have to.  It is made up of two parts: 1. the network layer (route model hook logic) that fetches the data you need && 2. a component that measures where it is at in the list.  If it breaks a threshold, it requests out to # 1 to fetch more data and expand the list.

**Comment by vinayak01** [comment]
@snewcomer It would be great if you give me an example for the requested question.

**Comment by snewcomer** [comment]
does the readme help?  let me know if we can make it better

**Comment by vinayak01** [comment]
Sure. Will look into it. 
Thanks.
