### ISSUE TITLE
TypeError: this.infinity.model is not a function

### ISSUE THREAD

**Issue by abulsayyad123** [ember-infinity/ember-infinity#375]
I am upgrading this plugin from `0.2.5` to `1.0.0`. My Ember app version is 2.14. I am trying to use service based approach to use ember-infinity. Earlier i was using Route Mixin approach. But on using service based approach I am getting `TypeError: this.infinity.model is not a function
` error. 

```
//I have imported infinity service
infinity: Ember.inject.service(),

someCP: Ember.computed(function() {
   return this.infinity.model('organisation');  //here I am getting error `this.infinity.model is not a function`
})
```
Is there any solution for this ?
Thanks

cc: @snewcomer

**Comment by snewcomer** [comment]
A part from jumping into your node_modules folder and checking ember-infinity to ensure the service && that hook exists, there might be a namespace class going on.

**Comment by snewcomer** [comment]
Also ensure you have the `~` operator so when you install it bumps the minor version to take care of any bugfixes and the like that may have went in after 1.0.

**Comment by abulsayyad123** [comment]
@snewcomer , issue is solved. I had to use `this.get('infinity').model`. But , pagination isn't working. On going to the end of page it showing text `Loading Infinite Model...`. 
In my .hbs file I am having following code:
```
{{#each filteredResults as |org|}}
{{/each}}
{{infinity-loader infinityModel=filteredResults}}
```
In controller file :
```
infinity: Ember.inject.service(),

filteredResults: Ember.computed(function() {
   return this.get('infinity').model('organisation'); 
})
```
Is there anything I am missing ?

**Comment by snewcomer** [comment]
maybe try it in the model hook of the route?

**Comment by abulsayyad123** [comment]
No luck on trying it in model, its still not working :(

**Comment by snewcomer** [comment]
See https://github.com/ember-infinity/ember-infinity#response-meta-expectations

Closing for now since no bugs, but feel free to keep the conversation going here if you need help!
