### ISSUE TITLE
Load ember-ajax API response data to `infinityModel`

### ISSUE THREAD

**Issue by rinoldsimon** [ember-infinity/ember-infinity#376]
For initial load, I make the query request in my controllers `init` hook and push the response data to `infinityModel` property.
```
import { A } from '@ember/array';
import { computed } from '@ember/object';

export default Controller.extend({
  peopleData: computed(() => A()),
  init() {
    this.get('ajax').request('/people', data: { ... }).then((response) => {
      this.set('peopleData', response);
    })
  }
});
```
API response:
```
{ 
  people: [
    { 
      name: 'Andrew Thomson',
      age: 32
    },
    { 
      name: 'Callum Falconer',
      age: 28
    },
    { 
      name: 'Evelia',
      age: 26
    },
    ...
  ],
 'meta': {
    'total': 20,
    'total_pages': 2,
    'page': 1
  }
}
```
Is this possible to load the above response data to `infinityModel` property? Will it work fine?
```
{{#each peopleData as |people|}}
  <h1>{{people.name}}</h1>
  <h2>{{people.age}}</h2>
{{/each}}

{{infinity-loader infinityModel=peopleData infinityLoad=(action "loadMore")}}
```
So when I reach the end of page will `loadMore` closure action will be triggered?
```
loadMore() {
  this.get('ajax').request('/people',  data: { ... }).then((response) => {
    this.get('peopleData').pushObject(response);
  })
}
```

Is this the right way I'm doing without routes model hook?

**Comment by snewcomer** [comment]
how is `data` initialized in your controller?  What is it's initial value?

**Comment by rinoldsimon** [comment]
say `data` is an array which is initialized as controller property
```
data: computed(() => A())
```
Updated the question as well

**Comment by snewcomer** [comment]
So in this case, you are only using the `infinity-loader` component.  Not the service or anything.  This addon might be overkill if you aren't using a `store` to managing fetching data.  You simply want a component that triggers `loadMore`...

Closing for now but we can keep having the conversation if you would like!
