### ISSUE TITLE
Is it possible to jump to the end of an infinite list?

### ISSUE THREAD

**Issue by LuisAverhoff** [ember-infinity/ember-infinity#387]
Given an infinite list and allowing the user to append items to the list as they are scrolling, is it possible to jump to the end of the infinite list when a new item gets added to the end of the list? Of course, when an item gets added to the end of the list, the user should be able to scroll back to previous items in the list; even ones that haven't been loaded yet?

**Comment by snewcomer** [comment]
@LuisAverhoff 👋 For jumping to the end of the list, you likely want to take advantage of closure actions and call `scrollIntoView` on the last item (ensuring the last item was loaded before calling it on an element)

- https://github.com/ember-infinity/ember-infinity#infinity-loader

For the second part of your question, I'm not totally sure what the question is....

**Comment by LuisAverhoff** [comment]
@newcomer Hey man thanks for replying. For the second part, I was thinking of a scenario where we have an infinite list of let say 100 items. Some of these items haven't been loaded i.e the infinity component hasn't fetched them yet. We append an item to the list and jump to the end of the list. Now, the user starts scrolling back and the expected response is for the infinity component to load them as these haven't fetch yet. Would I need to two infinity components for this? One for loading the previous page and one for the loading the next page

**Comment by LuisAverhoff** [comment]
Also scrollIntoView will only work if all items have been loaded. What if I'm in the middle of the list and I add an item? Calling scrollIntoView here won't jump me to the end of the list because I still have other items to load. This is my situation.

**Comment by snewcomer** [comment]
> the user should be able to scroll back to previous items in the list; even ones that haven't been loaded yet

Sorry I might be a little unaware of some details.  Specifically "scroll back to previous items".  I would assume that if those existed before you added new items to the list?

> Now, the user starts scrolling back and the expected response is for the infinity component to load these items since they been haven't fetch yet

That is to say, if my list starts at 0 and I scroll through 50 of them, all 50 of them should be there and fetched no matter where I scroll on the page.  The only ones not fetched are 50-100

So a couple of questions:
1.  Are we getting our directions messed up and this is something like a chat history?  

2.  Are you starting in the middle of the infinite list?  https://github.com/ember-infinity/ember-infinity#load-previous-pages

3.  When you replace the items in the list, is it replacing the entire list, thus causing state issues (like lazy loaded artwork)?

**Comment by LuisAverhoff** [comment]
Here are the details. The user loads the page for the first time and loads the first 25 items(Assume there are 100 items which means that are 4 pages). The user clicks on the button to add an item to the list. Without jumping to the end of the list, the user would have to load the 2 and 3 page before getting to the last page and finally seeing the item that they added. That is not the behavior I want. I want to be able to jump to the last page so the user can see the last item that they added. With this behavior, it is very possible that we jump to the end of the list before ember-infinity fetches all the items from the server.

To Address each of your questions.
 
1.)

I don't think we are getting our directions messed up. More than likely you are getting confused because I haven't articulate all the small details of this problem. Hopefully I have now but feel free to ask further questions if you feel that I haven't. 

2.) 

We always start in the beginning of the infinite list. The main difference between the demo that you have and my situation is that at any point in the list while we are **scrolling**, an item can be **appended** to it. The user can click on the button to append an item to the list the moment the user visit the page, the user visits the page, scroll to the middle of the list(loading half of the items in the list) and then finally clicks on the button(Now we need to be able to jump the list and skip loading all but the last page the item is in), the user can scroll all the way to the end of the list and click the button there(this is the best case scenario where are all the items have been loaded and we are at the end of the list). Heck we can scroll to the end of the list, scroll all the way back to the beginning of the list and click on the button to add an item to the list. Point is the list can be modified at any point in the list.

3.) 

we are only appending one item at a time. This is based on the click of a button.

**Comment by snewcomer** [comment]
closing as nothing we can do / or should do in this library!
