### ISSUE TITLE
Doesn't work with logged-in user

### ISSUE THREAD

**Issue by larryh** [ember-infinity/ember-infinity#392]
This doesn't even make sense to me, and I doubt it will to you, too - but one can always hope.

Your addon works flawlessly for me - as long as I don't have a logged-in user. When I log in... nothing.

I am just rendering a list of links, and nothing about them (both content and number) differs from a guest to a user.

The initial request is as expected, and the results returned from my server are as expected. 

As I guest, I have been able to scroll down over 100 items, 10 at a time. The exact same list for a logged-in user just sits there; no more requests for additional content are coming from the addon.

There are no errors in the console.

I use ember-simple-auth for authentication. The rest of the app works fine, it's just that when I log in, ember-infinity seems to die.

If you have any suggestions at all I would love to hear them, as I have spent hours banging my head against the wall with this problem.

However this works out: thanks for all of the work you do on this addon!

**Comment by larryh** [comment]
Okay, this turned out to be one of the most effed-up things I have ever seen. Documenting here in case anyone else runs into this problem.

The problem wasn't with ember-infinity (Way to go, guys and gals!), but with Firefox. (I use Ubuntu, maybe it's specific to that. Who knows?) Everything worked fine in Chrome on the desktop, and in the browsers for Android and iPhone.

Anyway, there was no ScrollEvent being issued when the scrollbar reached the bottom of the page - that's why ember-infinity wasn't asking for any more links.

Like I said, it happened only to a logged-in user. But in addition to that, I found one instance where the list of links was being returned, i.e. FF was firing a ScrollEvent, but for a whole class of other links it was not. 

Might help to think of a list of links for people, and a list of links for cities. When you were viewing a city and asked to see all links you got them - because a ScrollEvent was being fired when you got to the end of the list of links.

However, if you were viewing a person you would get one page of links. And when you scrolled down FF remained silent.

And if all of that wasn't bad enough - I found the actual culprit: it was simply an \<a\> tag that said something like "Show me the links". That \<a\> tag had a CSS bottom-margin set, among other things.

For the city (the one that worked) that was okay. However, it was that CSS bottom-margin setting that was preventing FF from firing the ScrollEvent at the end of the list for a person.

So I removed it. And guess what? The person links now worked like a charm, however, the city links stopped (because of no ScrollEvent). Are you effing kidding me?!!? (BTW, same behavior happened when I substituted padding-bottom for margin-bottom.)

So the way I finally got everything to work was if that <a> link appeared in the cities page I added a bottom-margin setting because it needed it or it would not work.

And if that \<a\> link appeared on the people page I had no bottom-margin setting, because if I did, it did not work.

Hours and hours and hours spent on this. And then management wonders why engineers hate schedules. :-)  (Sorry, just had to vent.)

**Comment by snewcomer** [comment]
@larryh Thanks for the issue!  What version are you on?  Does this issue happen if you hard refresh the app with a signed-in user?  This likely sounds like an application issue, perhaps an issue upstream.  One thing you can debug is with Chrome devtools - https://developers.google.com/web/updates/2015/05/automatically-pause-on-any-exception

**Comment by snewcomer** [comment]
Ah just saw this. Great glad you solved it!

**Comment by larryh** [comment]
You ain't the only one! :-)

Again, thanks for the great addon!
