### ISSUE TITLE
All records are erroneously marked as `isNew`

### ISSUE THREAD

**Issue by Redsandro** [ember-infinity/ember-infinity#393]
Certain functionality depends on knowing whether or not a record is _new_ or not. A record is new when you create something new on the client. A record is _not new_ when it is loaded from the server.

With ember-infinity, all records have their `isNew` boolean set to `true`. This breaks functionality, such as dirty tracking in serializers.

**Comment by snewcomer** [comment]
@Redsandro 👋 I'm not seeing this one the demo app.  Do you happen to have a reproduction to share?

**Comment by Redsandro** [comment]
Perhaps I can change the demo app to reproduce this, but the battery for my glasses is empty. Can you show me where exactly the demo source is?

**Comment by snewcomer** [comment]
Run `ember s` and the template is found is `app/tests/dummy/templates/demo.hbs`.  Lmk what you find!

**Comment by Redsandro** [comment]
@snewcomer I have to apologize. I was creating a testcase ([proof](https://github.com/ember-infinity/ember-infinity/pull/394/files)) and observed that your claim is correct. This means that I broke the expected behavior myself. I will investigate. Apologies.

The demo in this branch is working with a real json:api server, in case you ever need one quick.
