### ISSUE TITLE
infinity-loader needs to unhide on model change

### ISSUE THREAD

**Issue by Redsandro** [ember-infinity/ember-infinity#395]
The `infinity-loader` will stop functioning permanently on infinity when `hideOnInfinity=true`. However, when the model changes and has new content because of a change in filters (similar to #331), the `infinity-loader` should unhide itself because we've no longer reached infinity.

I think a property on the model should be watched inside the `infinity-loader` helper. Not sure what that property should be, but probably something like `isLoaded`, `isDoneLoading`, `canLoadMore` or something that resets when the model changes.

**Comment by Redsandro** [comment]
A workaround is to do check the model manually inside the helper:

```
{{#infinity-loader infinityModel=model hideOnInfinity=false}}
  {{#if model.canLoadMore}}
    <p>
      Loading
    </p>
  {{/if}}
{{/infinity-loader}}
```

But a helper should help, so this is what we're trying to do:

```
{{infinity-loader infinityModel=model hideOnInfinity=true loadingText="Loading"}}
```

**Comment by snewcomer** [comment]
@Redsandro Are you looking for the `infinity-loader` component to `yield` out some of it's properties so you can use it in block form?  If so, that seems like a good idea!

**Comment by Redsandro** [comment]
I'm glad it's a good idea, but that's not really what I mean. :sweat_smile: 

The short non-# form (second example) is a nice and short ~~helper~~ component, making our lives and code easier. Clever ~~helper~~ component.

When the ~~helper~~ component hides itself (`hideOnInfinity=true`) because there are no more records to fetch in the `InfinityModel`, this is also expected and desired.

However, when the `InfinityModel` _changes_ because filters are applied to the model, the ~~helper~~ component should _unhide_ itself. Otherwise, once the model changes, the `InfinityModel` is broken.

I created the above workaround, but it's 700% more lines of code. :see_no_evil:

**Comment by Redsandro** [comment]
> A workaround is to do check the model manually inside the helper:
> 
> ```
> {{#infinity-loader infinityModel=model hideOnInfinity=false}}
>   {{#if model.canLoadMore}}
>     <p>
>       Loading
>     </p>
>   {{/if}}
> {{/infinity-loader}}
> ```

This actually does not work when the model reloads and the trigger component is on the screen. It will stay visible permanently. The trigger needs to scroll into view for the `canLoadMore` to be set to false after filtering the model. How can we work around this?

**Comment by jagthedrummer** [comment]
I've been struggling with this same problem, and the workaround suggested here worked for me:

https://github.com/ember-infinity/ember-infinity/issues/327#issuecomment-424682504

**Comment by snewcomer** [comment]
Thank you for the issue!  What we ultimately need to do is observe `reachedInfinity` and reset `isVisible` when it changes to `false`.  #413 

One way, we can move away from observers, but for now I think the referenced PR fixes it.

**Comment by Redsandro** [comment]
Does this mean we can use the one-liner again without wrapping it in `{{#unless model.reachedInfinity}}`? That would be great!
