### ISSUE TITLE
infinityLoader renders JSON response data twice

### ISSUE THREAD

**Issue by kushthedude** [ember-infinity/ember-infinity#411]
We are using emberInfinity as primary loader in our production application. The Loader is rendering the server response twice and causing discrepancies . After removing the infinityLoader the items are getting rendered correctly.
Our router query Using Infinity Loader:
```js
 return this.infinity.model('sessions', {		     
       include      : 'event',		       
       filter       : filterOptions,		       
       sort         : 'starts-at',		       
       perPage      : 10,		       
       startingPage : 1,		
       perPageParam : 'page[size]',		
       pageParam    : 'page[number]',		
       store        : this.authManager.currentUser
}
```

Without Infinity Loader : 
```js
return this.authManager.currentUser.query('sessions', {
     	       include      : 'event',
       	       filter       : filterOptions,
       	       'page[size]' : 0,
       	       sort         : 'starts-at'
}
```

For more reference you may see https://github.com/fossasia/open-event-frontend/pull/3811
It would be great if there is any help regarding.
PS: InfinityLoader is working perfectly in other places of our app

**Comment by kushthedude** [comment]
cc: @snewcomer @hhff

**Comment by snewcomer** [comment]
@kushthedude 👋 Thank you for the issue!  I'm unable to pin down where this might be in this repo.

My first instinct is that it might be in the app code, specifically related to your use of the `{{infinity-loader}}` component.  In the referenced PR, I've added another test for custom store behaviour.

**Comment by kushthedude** [comment]
@snewcomer here is our template file
```js
{{#each model as |session|}} {{session-card session=session}} <div class="ui hidden divider"></div> {{else}} <div class="ui disabled header">{{t 'No session proposals found for the events'}}</div> {{/each}} {{#infinity-loader infinityModel=model}} <div class="ui loading very padded basic segment"> </div> {{infintyModel.reachedInfinity}} {{/infinity-loader}}
```

**Comment by kushthedude** [comment]
Resolved, It was a problem on our side.
Thank @snewcomer for the quick response! 😄
