### ISSUE TITLE
2.1.0 throws an EEXIST: file already exists on app build

### ISSUE THREAD

**Issue by maartenparmentier** [ember-infinity/ember-infinity#417]
Hi there!

We've been using this addon for ages and never had issues.
The last release (2.1.0) however breaks our build

`
EmberCli::BuildError - :frontend has failed to build: Error: EEXIST: file already exists, symlink 'xxx/frontend/node_modules/ember-infinity/app/templates/components/infinity-loader.js' -> '/var/folders/f_/3tsbxd_121qfwtpmt9bbn_qc0000gn/T/broccoli-53081Is43Nt4o2pvj/out-787-broccoli_persistent_filter_template_compiler/intuo-ember/templates/components/infinity-loader.js'
`

We are using a custom template (generated by the `ember generate infinity-template` command stated in the readme)

I think it's related to [this ember-cli issue](https://github.com/ember-cli/ember-cli/issues/5336). But I can't seem to fix it 😬

**Comment by snewcomer** [comment]
Woah.  Yes you are correct.  That would definitely prevent you from upgrading.  I'll see if I can look into it tomorrow.

**Comment by snewcomer** [comment]
If this is a long outstanding bug, we may need to simply change the blueprint to generate a new filename.  What do you think?  It was a "breaking change" from the perspective of the framework when I introduced the templated infinity-loader in this addon for 2.1.0.  I'm not sure of another solution....

**Comment by maartenparmentier** [comment]
I think that's a valid idea and solution. 👍

**Comment by snewcomer** [comment]
Hm.  A slight nuisance with that this approach would require you to import and extend from the addon's `infinity-loader.js` class...We may have to suggest that approach in the README.

I'm also wondering if the errors is due to how we are exporting our template in `app/`.  Will look into that next.

**Comment by brunoocasali** [comment]
Hey @snewcomer how can I do the approach you mentioned above? (I'm really interested in this fix, my build is broken too 💃)

**Comment by mk-conn** [comment]
> Hey @snewcomer how can I do the approach you mentioned above? (I'm really interested in this fix, my build is broken too 💃)

Yep, would be interested in that workaround too... :)

**Comment by snewcomer** [comment]
@maartenparmentier I'm going to give #423 a try...I'm unsure that, if because it is exporting the template, that is is causing the build issues you are seeing.  By removing it, it "may" help.

**Comment by maartenparmentier** [comment]
@snewcomer It works! Thanks your for this 🙏 👍
