### ISSUE TITLE
Is it possible to use this component with a horizontal list?

### ISSUE THREAD

**Issue by tonyown1** [ember-infinity/ember-infinity#418]
Hi, I have columns with a bunch of div components I load in it. It works fine if I load them vertically but horizontally I am having trouble. Every time I scroll unitl the end of the div to trigger the Infinity-Loader, it keeps fetching my information until the whole list is loaded. It's as if the loader is rendered in the viewPort constantly. Any tips or workaround ?

**Comment by snewcomer** [comment]
@tonyown1 👋 What version are you on?

**Comment by tonyown1** [comment]
@snewcomer  Hiya, my ember version is 3.15.1

**Comment by snewcomer** [comment]
@tonyown1 I added a quick example in the dummy app.  It looks like it is working.  What version of ember-infinity are you on?

https://github.com/ember-infinity/ember-infinity/commit/786b4e250095ad7a744101a31b8a7844df3e69e1

**Comment by tonyown1** [comment]
Superb, thanks for the quick response, but it still doesn't work. Some issue with my one of my component being inside my item is triggering it to fetch all the info constantly. When I remove that component from my item, it works perfectly fine. I think it's a css issue. I'll try to figure it out, but for me this issue is resolved. 

Thanks again!

**Comment by snewcomer** [comment]
@tonyown1 Oh one thing came to mind.  Ensure you "sentinel" has min height of 1px and min width of 1px. I've run into a bunch of trouble when the "sentinel" ("infinity-loader") doesn't have both.

**Comment by snewcomer** [comment]
closing for now!!
